### ISSUE TITLE
Webkit2gtk dependency change

### ISSUE THREAD

**Issue by ghost** [0xBOBF/gnome-slackware-15.0#11]
Slackbuilds have updated webkit2gtk to version 2.4 which adds "unifdef" as a dependency.

**Comment by ghost** [comment]
and I now see that's updated in the gnome41 branch.

**Comment by 0xBOBF** [comment]
Yes I updated in the gnome-41 branch, but then forgot to fix the main branch, so thanks for the reminder. 

Note that the slackware-15.0 build still uses the webkit2gtk 4.0 API, which uses soup2 still. Just needed to add the unifdef dependency to fix this build.

Some of the builds in the gnome-41 branch are not on slackbuilds.org yet. I am still doing some runtime testing before submitting those builds. Once that's settled, the main and gnome-41 branches will be merged again, but for now only the queue files from the main branch will properly build (with sbopkg for example).

**Comment by ghost** [comment]
Thanks for the clarification.
