### ISSUE TITLE
Highlight lua dependency changed

### ISSUE THREAD

**Issue by seb62** [0xBOBF/gnome-slackware-15.0#6]
Hi,
It seems that lua53 replace lua as a dependency for highlight.
Thanks.

**Comment by 0xBOBF** [comment]
Thanks for the report. I've updated the gnome-all.sqf queue file and confirmed the full build completes without issue.

Commit: https://github.com/0xBOBF/gnome-slackware-15.0/commit/2325e48e1a2e3a1bacc67efdd3abbdf2a132bdc9
